framework:
    asset_mapper:
        # Assets are organized by context under assets/admin, assets/web and assets/controllers.
        paths:
            - assets/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
