doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        # Ruta según DATABASE_ENGINE (.env): migrations/postgresql | migrations/mysql
        'DoctrineMigrations': '%kernel.project_dir%/migrations/%env(DATABASE_ENGINE)%'
    enable_profiler: false
