twig:
    file_name_pattern: '*.twig'
    
    # Registro de alias para tus contextos
    paths:
        '%kernel.project_dir%/templates/admin': admin
        '%kernel.project_dir%/templates/web': web

when@test:
    twig:
        strict_variables: true
