<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260829200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create general_settings table for platform-wide configuration';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE general_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, show_hidden_users BOOLEAN DEFAULT true NOT NULL, enabled_languages JSON NOT NULL, website_default_language VARCHAR(5) NOT NULL, last_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE general_settings');
    }
}
