<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create pokemon_image table for Pokémon multimedia gallery';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pokemon_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pokemon_id INT NOT NULL, image_path VARCHAR(512) NOT NULL, description VARCHAR(255) DEFAULT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_POKEMON_IMAGE_POKEMON ON pokemon_image (pokemon_id)');
        $this->addSql('ALTER TABLE pokemon_image ADD CONSTRAINT FK_POKEMON_IMAGE_POKEMON FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pokemon_image DROP CONSTRAINT FK_POKEMON_IMAGE_POKEMON');
        $this->addSql('DROP TABLE pokemon_image');
    }
}
