<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261003230000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create legal documents, versions, translations and user acceptances';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE legal_documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, name VARCHAR(180) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_legal_documents_type ON legal_documents (type)');

        $this->addSql('CREATE TABLE legal_document_versions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_number INT NOT NULL, status VARCHAR(16) NOT NULL, requires_reacceptance BOOLEAN NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_title VARCHAR(180) DEFAULT NULL, notification_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_legal_document_version_number ON legal_document_versions (document_id, version_number)');
        $this->addSql('CREATE INDEX idx_legal_document_versions_status ON legal_document_versions (document_id, status)');
        $this->addSql('CREATE INDEX IDX_LEGAL_DOCUMENT_VERSIONS_CREATED_BY ON legal_document_versions (created_by_id)');
        $this->addSql('ALTER TABLE legal_document_versions ADD CONSTRAINT FK_LEGAL_DOCUMENT_VERSIONS_DOCUMENT FOREIGN KEY (document_id) REFERENCES legal_documents (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE legal_document_versions ADD CONSTRAINT FK_LEGAL_DOCUMENT_VERSIONS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE legal_document_version_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, language VARCHAR(5) NOT NULL, title VARCHAR(180) NOT NULL, content_html TEXT NOT NULL, acceptance_label VARCHAR(255) NOT NULL, summary TEXT DEFAULT NULL, content_hash VARCHAR(64) DEFAULT NULL, version_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_legal_translation_version_language ON legal_document_version_translations (version_id, language)');
        $this->addSql('ALTER TABLE legal_document_version_translations ADD CONSTRAINT FK_LEGAL_TRANSLATIONS_VERSION FOREIGN KEY (version_id) REFERENCES legal_document_versions (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE user_legal_acceptances (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, language VARCHAR(5) NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(512) DEFAULT NULL, method VARCHAR(32) NOT NULL, content_hash VARCHAR(64) NOT NULL, user_id INT NOT NULL, version_id INT NOT NULL, translation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_legal_acceptance_version ON user_legal_acceptances (user_id, version_id)');
        $this->addSql('CREATE INDEX idx_user_legal_acceptances_user ON user_legal_acceptances (user_id)');
        $this->addSql('CREATE INDEX IDX_USER_LEGAL_ACCEPTANCES_VERSION ON user_legal_acceptances (version_id)');
        $this->addSql('CREATE INDEX IDX_USER_LEGAL_ACCEPTANCES_TRANSLATION ON user_legal_acceptances (translation_id)');
        $this->addSql('ALTER TABLE user_legal_acceptances ADD CONSTRAINT FK_USER_LEGAL_ACCEPTANCES_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_legal_acceptances ADD CONSTRAINT FK_USER_LEGAL_ACCEPTANCES_VERSION FOREIGN KEY (version_id) REFERENCES legal_document_versions (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_legal_acceptances ADD CONSTRAINT FK_USER_LEGAL_ACCEPTANCES_TRANSLATION FOREIGN KEY (translation_id) REFERENCES legal_document_version_translations (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_legal_acceptances DROP CONSTRAINT FK_USER_LEGAL_ACCEPTANCES_USER');
        $this->addSql('ALTER TABLE user_legal_acceptances DROP CONSTRAINT FK_USER_LEGAL_ACCEPTANCES_VERSION');
        $this->addSql('ALTER TABLE user_legal_acceptances DROP CONSTRAINT FK_USER_LEGAL_ACCEPTANCES_TRANSLATION');
        $this->addSql('DROP TABLE user_legal_acceptances');
        $this->addSql('ALTER TABLE legal_document_version_translations DROP CONSTRAINT FK_LEGAL_TRANSLATIONS_VERSION');
        $this->addSql('DROP TABLE legal_document_version_translations');
        $this->addSql('ALTER TABLE legal_document_versions DROP CONSTRAINT FK_LEGAL_DOCUMENT_VERSIONS_DOCUMENT');
        $this->addSql('ALTER TABLE legal_document_versions DROP CONSTRAINT FK_LEGAL_DOCUMENT_VERSIONS_CREATED_BY');
        $this->addSql('DROP TABLE legal_document_versions');
        $this->addSql('DROP TABLE legal_documents');
    }
}
