<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261003031312 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create notifications inbox table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(64) NOT NULL, title VARCHAR(180) NOT NULL, message TEXT NOT NULL, action_url VARCHAR(512) DEFAULT NULL, payload JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, recipient_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_notifications_recipient_read ON notifications (recipient_id, read_at)');
        $this->addSql('CREATE INDEX idx_notifications_recipient_created ON notifications (recipient_id, created_at)');
        $this->addSql('CREATE INDEX IDX_NOTIFICATIONS_ACTOR ON notifications (actor_id)');
        $this->addSql('CREATE INDEX IDX_6000B0D3E92F8F78 ON notifications (recipient_id)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D310DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3E92F8F78');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D310DAF24A');
        $this->addSql('DROP TABLE notifications');
    }
}
